# Alembic Configuration File

[alembic]
# path to migration scripts
sqlalchemy.url = driver://user:password@localhost/dbname
scripts_location = alembic

# template used to generate migration file names; The default value is %%(rev)s_%%(slug)s
# Uncomment the line below if you want the files to be prepended with date and time
#file_template = %%(rev)s_%%(slug)s

# sys.path path, will be prepended to sys.path if present
# defaults to the current working directory
prepend_sys_path = .

# timezone to use when rendering the date
# within the migration file as well as the filename.
# string value is passed to the constructor of datetime.datetime
# Leave blank for localtime
# timezone =

# max length of characters to apply to the
# "slug" field of a filename, or None if
# there is no max
# truncate_slug_len = 40

# set to 'true' to run the environment during
# the 'revision' command, regardless of autogenerate
# revision_environment = false

# set to 'true' to allow .pyc and .pyo files without
# a source .py file to be detected as revisions in the
# versions/ directory
# sourceless = false

# logging configuration
# Loggers to set up, of the form key is logger name, value is
# logger level
# logger_handlers =
# level = WARN

# If set to 'true', the enabled logger handler is sqlalchemy.engine,
# by default set requests are logged
# sqlalchemy_echo =

# A list of logger names to setup the logging level
# messages:
# FORMAT: logger_handler_name:LEVEL:logger_name (separated by ;)
# e.g. WatchDog:DEBUG:sqlalchemy.engine
# example_logger: sqlalchemy_pool:WARN:example_logger

# set to 'true' to let user fully control sqlalchemy logging
# in [logger_sqlalchemy] sections
# use_logging_config = false


[loggers]
keys = root,sqlalchemy

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
