[pytest]
filterwarnings =
    ignore::DeprecationWarning:pytest_asyncio.plugin
    ignore::DeprecationWarning:fastapi.routing
    ignore::DeprecationWarning:starlette._utils
    ignore::DeprecationWarning:jose.jwt
    ignore::SyntaxWarning:anyio.from_thread
