import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import type { PersonaResponse } from '@/types/api'
import { PERSONA_FIELD_LABELS } from '@/types/api'

const FIELD_ORDER = [
  'name_title',
  'goals',
  'pain_points',
  'decision_drivers',
  'false_beliefs',
  'job_to_be_done',
  'usage_patterns',
  'objections',
  'success_metrics',
] as const

const QUALITY_VARIANTS: Record<string, 'secondary' | 'default' | 'outline'> = {
  low: 'outline',
  medium: 'secondary',
  high: 'default',
}

interface Props {
  persona: PersonaResponse
  projectName: string
}

function buildPersonaMarkdown(persona: PersonaResponse, projectName: string): string {
  const lines: string[] = [
    `# Persona — ${projectName}`,
    '',
    `**Completion:** ${Math.round(persona.completion_pct * 100)}%`,
    persona.confidence_score != null
      ? `**Confidence:** ${Math.round(persona.confidence_score * 100)}%`
      : '',
    persona.last_analyzed_at
      ? `**Last analyzed:** ${new Date(persona.last_analyzed_at).toLocaleString()}`
      : '',
    persona.staleness_decay_pct > 0
      ? `*Staleness decay: -${Math.round(persona.staleness_decay_pct * 100)}%*`
      : '',
    '',
    '---',
    '',
  ].filter(Boolean)

  for (const key of FIELD_ORDER) {
    const label = PERSONA_FIELD_LABELS[key]
    const value = persona[key as keyof PersonaResponse]
    const quality = persona.field_quality?.[key]
    if (label && (value != null && String(value).trim() !== '')) {
      lines.push(`## ${label}`)
      if (quality) lines.push(`*Evidence: ${quality}*`)
      lines.push('')
      lines.push(String(value).trim())
      lines.push('')
    }
  }

  lines.push('---')
  lines.push(`*Generated by Discovery App · ${new Date().toISOString()}*`)
  return lines.join('\n')
}

function downloadMarkdown(content: string, projectName: string) {
  const blob = new Blob([content], { type: 'text/markdown' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `persona-${projectName.replace(/\s+/g, '-')}.md`
  a.click()
  URL.revokeObjectURL(url)
}

export function PersonaCard({ persona, projectName }: Props) {
  const completionPct = Math.round(persona.completion_pct * 100)
  const hasStaleness = persona.staleness_decay_pct > 0
  const monthsStale = persona.last_analyzed_at
    ? Math.max(0, (Date.now() - new Date(persona.last_analyzed_at).getTime()) / (30 * 24 * 60 * 60 * 1000))
    : 0

  const handleDownload = () => {
    const md = buildPersonaMarkdown(persona, projectName)
    downloadMarkdown(md, projectName)
  }

  return (
    <section aria-label="Persona card" className="space-y-4">
      <div className="flex flex-wrap items-center justify-between gap-2">
        <h2 className="text-lg font-semibold">Persona</h2>
        <div className="flex items-center gap-2">
          <span className="text-sm text-muted-foreground">
            {completionPct}% complete
          </span>
          {persona.confidence_score != null && (
            <span className="text-sm">
              {Math.round(persona.confidence_score * 100)}% confidence
            </span>
          )}
          <Button variant="outline" size="sm" onClick={handleDownload}>
            Download .md
          </Button>
        </div>
      </div>

      {hasStaleness && (
        <p className="text-xs text-muted-foreground">
          Staleness: -{Math.round(persona.staleness_decay_pct * 100)}%
          {monthsStale >= 1 && ` (${Math.floor(monthsStale)} month${monthsStale >= 2 ? 's' : ''} since last analysis)`}
        </p>
      )}

      <div className="space-y-3">
        {FIELD_ORDER.map((key) => {
          const label = PERSONA_FIELD_LABELS[key]
          const value = persona[key as keyof PersonaResponse]
          const quality = persona.field_quality?.[key]
          const hasValue = value != null && String(value).trim() !== ''
          if (!label) return null
          return (
            <div key={key} className="border-b border-border/50 pb-3 last:border-0">
              <div className="flex flex-wrap items-center gap-2 mb-1">
                <span className="text-sm font-medium">{label}</span>
                {quality && (
                  <Badge variant={QUALITY_VARIANTS[quality] ?? 'outline'} className="text-xs">
                    {quality}
                  </Badge>
                )}
              </div>
              <p className="text-sm text-muted-foreground">
                {hasValue ? String(value).trim() : '—'}
              </p>
            </div>
          )
        })}
      </div>
    </section>
  )
}
