import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import type { IcpResponse } from '@/types/api'
import { ICP_DIMENSION_LABELS } from '@/types/api'

const DIMENSION_ORDER = [
  'company_size',
  'industries',
  'geography',
  'revenue',
  'tech_stack',
  'use_case_fit',
  'buying_process',
  'budget',
  'maturity',
  'custom',
] as const

const QUALITY_VARIANTS: Record<string, 'secondary' | 'default' | 'outline'> = {
  low: 'outline',
  medium: 'secondary',
  high: 'default',
}

interface Props {
  icp: IcpResponse
  projectName: string
}

function buildIcpMarkdown(icp: IcpResponse, projectName: string): string {
  const lines: string[] = [
    `# Ideal Customer Profile — ${projectName}`,
    '',
    icp.confidence_score != null
      ? `**Overall confidence:** ${Math.round(icp.confidence_score * 100)}%`
      : '',
    icp.last_analyzed_at
      ? `**Last analyzed:** ${new Date(icp.last_analyzed_at).toLocaleString()}`
      : '',
    '',
    '---',
    '',
  ].filter(Boolean)

  for (const key of DIMENSION_ORDER) {
    const label = ICP_DIMENSION_LABELS[key]
    const value = icp[key as keyof IcpResponse]
    const quality = icp.dimension_confidence?.[key]
    if (label && (value != null && String(value).trim() !== '')) {
      lines.push(`## ${label}`)
      if (quality) lines.push(`*Confidence: ${quality}*`)
      lines.push('')
      lines.push(String(value).trim())
      lines.push('')
    }
  }

  lines.push('---')
  lines.push(`*Generated by Discovery App · ${new Date().toISOString()}*`)
  return lines.join('\n')
}

function downloadMarkdown(content: string, projectName: string) {
  const blob = new Blob([content], { type: 'text/markdown' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `icp-${projectName.replace(/\s+/g, '-')}.md`
  a.click()
  URL.revokeObjectURL(url)
}

export function IcpCard({ icp, projectName }: Props) {
  const handleDownload = () => {
    const md = buildIcpMarkdown(icp, projectName)
    downloadMarkdown(md, projectName)
  }

  return (
    <section aria-label="ICP card" className="space-y-4">
      <div className="flex flex-wrap items-center justify-between gap-2">
        <h2 className="text-lg font-semibold">Ideal Customer Profile</h2>
        <div className="flex items-center gap-2">
          {icp.confidence_score != null && (
            <span className="text-sm">
              {Math.round(icp.confidence_score * 100)}% confidence
            </span>
          )}
          <Button variant="outline" size="sm" onClick={handleDownload}>
            Download .md
          </Button>
        </div>
      </div>

      <div className="space-y-3">
        {DIMENSION_ORDER.map((key) => {
          const label = ICP_DIMENSION_LABELS[key]
          const value = icp[key as keyof IcpResponse]
          const quality = icp.dimension_confidence?.[key]
          const hasValue = value != null && String(value).trim() !== ''
          if (!label) return null
          return (
            <div key={key} className="border-b border-border/50 pb-3 last:border-0">
              <div className="flex flex-wrap items-center gap-2 mb-1">
                <span className="text-sm font-medium">{label}</span>
                {quality && (
                  <Badge variant={QUALITY_VARIANTS[quality] ?? 'outline'} className="text-xs">
                    {quality}
                  </Badge>
                )}
              </div>
              <p className="text-sm text-muted-foreground">
                {hasValue ? String(value).trim() : '—'}
              </p>
            </div>
          )
        })}
      </div>
    </section>
  )
}
